; Temporarily disabled due to missing Utils.Rhyme_data_utils module
;(executable
; (public_name rhyme_benchmark)
; (name benchmark_rhyme_utils)
; (libraries yyocamlc.utils))

(executable
 (public_name simple_string_benchmark)
 (name simple_string_benchmark)
 (libraries)
 (modules simple_string_benchmark))
