(library
 (public_name yyocamlc.poetry.data)
 (name poetry_data)
 (modules
  word_class_types
  an_yun_data
  expanded_word_class_data
  unified_data_loader
  unified_data_loader_extended
  unified_data_loader_comprehensive
  poetry_data_loader_compat
  expanded_data_loader
  poetry_json_parser
  poetry_file_reader
  poetry_data_fallback
  poetry_word_class_loader
  externalized_data_loader
  json_parser
  file_helper
  data_source_manager
  cache_manager
  poetry_data_loader
  tone_data_loader
  data_source_registry
  rhyme_data_loader
  data_manager_types
  data_manager_query
  data_manager_storage
  data_manager_lookup
  data_manager_compat
  data_manager)
 (libraries
  yyocamlc_lib
  unix
  rhyme_groups
  poetry_tone_data
  yojson
  poetry_data_core
  poetry_data_managers
  poetry_data_loaders))
