(library
 (public_name yyocamlc.poetry.artistic)
 (name poetry_artistic)
 (modules
  artistic_engine_unified
  artistic_evaluators  
  artistic_data_manager
  artistic_standards
  artistic_cache
  artistic_compatibility
  artistic_metrics
  artistic_reporting)
 (libraries
  yyocamlc_lib
  poetry_core
  utils)
 (flags
  (:standard)))