(** 骆言词法分析器 - 文言风格关键字 *)

(** 文言风格关键字，支持古代汉语编程语法 *)
type wenyan_keyword =
  (* 基础文言关键字 *)
  | HaveKeyword  (** 吾有 - I have *)
  | OneKeyword  (** 一 - one *)
  | NameKeyword  (** 名曰 - name it *)
  | SetKeyword  (** 设 - set *)
  | AlsoKeyword  (** 也 - also/end particle *)
  | ThenGetKeyword  (** 乃 - then/thus *)
  | CallKeyword  (** 曰 - called/said *)
  | ValueKeyword  (** 其值 - its value *)
  | AsForKeyword  (** 为 - as for/regarding *)
  | NumberKeyword  (** 数 - number *)
  (* 文言扩展关键字 *)
  | WantExecuteKeyword  (** 欲行 - want to execute *)
  | MustFirstGetKeyword  (** 必先得 - must first get *)
  | ForThisKeyword  (** 為是 - for this *)
  | TimesKeyword  (** 遍 - times/iterations *)
  | EndCloudKeyword  (** 云云 - end marker *)
  | IfWenyanKeyword  (** 若 - if (wenyan style) *)
  | ThenWenyanKeyword  (** 者 - then particle *)
  | GreaterThanWenyan  (** 大于 - greater than *)
  | LessThanWenyan  (** 小于 - less than *)
  (* 自然语言函数定义关键字 *)
  | DefineKeyword  (** 定义 - define *)
  | AcceptKeyword  (** 接受 - accept *)
  | ReturnWhenKeyword  (** 时返回 - return when *)
  | ElseReturnKeyword  (** 否则返回 - else return *)
  | MultiplyKeyword  (** 乘以 - multiply *)
  | DivideKeyword  (** 除以 - divide *)
  | AddToKeyword  (** 加上 - add to *)
  | SubtractKeyword  (** 减去 - subtract *)
  | IsKeyword  (** 为 - is *)
  | EqualToKeyword  (** 等于 - equal to *)
  | LessThanEqualToKeyword  (** 小于等于 - less than or equal to *)
  | FirstElementKeyword  (** 首元素 - first element *)
  | RemainingKeyword  (** 剩余 - remaining *)
  | EmptyKeyword  (** 空 - empty *)
  | CharacterCountKeyword  (** 字符数量 - character count *)
  | OfParticle  (** 之 - possessive particle *)
  | TopicMarker  (** 者 - topic marker *)
  (* 新增自然语言函数定义关键字 *)
  | InputKeyword  (** 输入 - input *)
  | OutputKeyword  (** 输出 - output *)
  | MinusOneKeyword  (** 减一 - minus one *)
  | PlusKeyword  (** 加 - plus *)
  | WhereKeyword  (** 其中 - where *)
  | SmallKeyword  (** 小 - small *)
  | ShouldGetKeyword  (** 应得 - should get *)
  | IntTypeKeyword  (** 整数 - int *)
  | FloatTypeKeyword  (** 浮点数 - float *)
  | StringTypeKeyword  (** 字符串 - string *)
  | BoolTypeKeyword  (** 布尔 - bool *)
  | UnitTypeKeyword  (** 单元 - unit *)
  | ListTypeKeyword  (** 列表 - list *)
  | ArrayTypeKeyword  (** 数组 - array *)
  | VariantKeyword  (** 变体 - variant *)
  | TagKeyword  (** 标签 - tag (for polymorphic variants) *)
[@@deriving show, eq]

val to_string : wenyan_keyword -> string
(** 将文言关键字转换为字符串表示 *)

val from_string : string -> wenyan_keyword option
(** 将字符串转换为文言关键字（如果匹配） *)

val is_basic_wenyan : wenyan_keyword -> bool
(** 检查是否为基础文言关键字 *)

val is_math_operation : wenyan_keyword -> bool
(** 检查是否为数学运算关键字 *)

val is_type_keyword : wenyan_keyword -> bool
(** 检查是否为类型相关关键字 *)
