(library
 (public_name yyocamlc.utils)
 (name utils)
 (modules
  base_formatter
  base_string_ops
  buffer_formatting_utils
  error_formatters
  position_formatters
  syntax_formatters
  analysis_formatters
  unified_error_formatter
  validation_utils
  conversion_utils
  error_handling_utils
  common_patterns
  token_processing_utils
  rhyme_file_config
  rhyme_json_parser
  rhyme_data_cache
  rhyme_data_utils)
 (libraries str yojson unix))
