#!/bin/bash

# ASCII字符批量清理脚本
# 用于清理所有.ly文件中的ASCII字符，保持注释中的ASCII字符
# 根据Issue #201的要求进行完整清理

set -e

echo "🧹 开始批量清理.ly文件中的ASCII字符..."
echo "📝 注意: 保留注释中的ASCII字符"

# ASCII字符映射表
declare -A char_map=(
    # ASCII字母替换为中文
    ["AI"]="人工智能"
    ["API"]="接口"
    ["ID"]="标识"
    ["URL"]="链接"
    ["HTML"]="网页"
    ["CSS"]="样式"
    ["JS"]="脚本"
    ["JSON"]="数据"
    ["XML"]="标记"
    ["HTTP"]="协议"
    ["HTTPS"]="安全协议"
    ["FTP"]="文件传输"
    ["SQL"]="查询语言"
    ["TCP"]="传输协议"
    ["UDP"]="用户数据报协议"
    ["IP"]="网际协议"
    ["DNS"]="域名系统"
    ["CPU"]="处理器"
    ["GPU"]="图形处理器"
    ["RAM"]="内存"
    ["ROM"]="只读存储器"
    ["USB"]="通用串行总线"
    ["WiFi"]="无线网络"
    ["VPN"]="虚拟专用网络"
    ["SSH"]="安全外壳"
    ["SSL"]="安全套接层"
    ["TLS"]="传输层安全"
    ["MD5"]="消息摘要算法"
    ["SHA"]="安全散列算法"
    ["UTF"]="统一码转换格式"
    ["ASCII"]="美国信息交换标准代码"
    ["Unicode"]="统一码"
    ["Base64"]="六十四进制编码"
    ["Regex"]="正则表达式"
    ["CLI"]="命令行界面"
    ["GUI"]="图形用户界面"
    ["UI"]="用户界面"
    ["UX"]="用户体验"
    ["CMS"]="内容管理系统"
    ["ERP"]="企业资源规划"
    ["CRM"]="客户关系管理"
    ["IoT"]="物联网"
    ["AR"]="增强现实"
    ["VR"]="虚拟现实"
    ["AI友好"]="人工智能友好"
    
    # 标点符号替换
    [":"]="："
    [";"]="；"
    [","]="，"
    ["."]="。"
    ["?"]="？"
    ["!"]="！"
    ["("]="（"
    [")"]="）"
    ["["]="「"
    ["]"]="」"
    ["{"]="『"
    ["}"]="』"
    ["\""]="「"
    ["'"]="」"
    ["<"]="〈"
    [">"]="〉"
    ["/"]="／"
    ["\\"]="＼"
    ["|"]="｜"
    ["&"]="＆"
    ["*"]="＊"
    ["+"]="＋"
    ["-"]="－"
    ["="]="＝"
    ["_"]="下划线"
    ["@"]="在"
    ["#"]="号"
    ["$"]="元"
    ["%"]="百分之"
    ["^"]="异或"
    ["\`"]="反引号"
    ["~"]="波浪号"
)

# 特殊字符序列替换
declare -A sequence_map=(
    # 编程相关术语
    ["List点"]="列表点"
    ["Char点"]="字符点"
    ["String点"]="字符串点"
    ["Unix点"]="系统点"
    ["Float点"]="浮点点"
    ["C代码"]="丙代码"
    [" C "]=" 丙 "
    ["ASCII"]="美国信息交换标准代码"
    ["List"]="列表"
    ["Char"]="字符"
    ["String"]="字符串"
    ["Unix"]="系统"
    ["Float"]="浮点"
    ["PR"]="拉取请求"
    ["CI"]="持续集成"
    ["API"]="接口"
    ["URL"]="链接"
    ["HTML"]="网页"
    ["CSS"]="样式"
    ["JSON"]="数据"
    ["XML"]="标记"
    ["HTTP"]="协议"
    ["HTTPS"]="安全协议"
    ["FTP"]="文件传输"
    ["SQL"]="查询语言"
    ["TCP"]="传输协议"
    ["UDP"]="用户数据报协议"
    ["IP"]="网际协议"
    ["DNS"]="域名系统"
    ["CPU"]="处理器"
    ["GPU"]="图形处理器"
    ["RAM"]="内存"
    ["ROM"]="只读存储器"
    ["USB"]="通用串行总线"
    ["WiFi"]="无线网络"
    ["VPN"]="虚拟专用网络"
    ["SSH"]="安全外壳"
    ["SSL"]="安全套接层"
    ["TLS"]="传输层安全"
    ["MD5"]="消息摘要算法"
    ["SHA"]="安全散列算法"
    ["UTF"]="统一码转换格式"
    ["Unicode"]="统一码"
    ["Base64"]="六十四进制编码"
    ["Regex"]="正则表达式"
    ["CLI"]="命令行界面"
    ["GUI"]="图形用户界面"
    ["UI"]="用户界面"
    ["UX"]="用户体验"
    ["CMS"]="内容管理系统"
    ["ERP"]="企业资源规划"
    ["CRM"]="客户关系管理"
    ["IoT"]="物联网"
    ["AR"]="增强现实"
    ["VR"]="虚拟现实"
    ["AI友好"]="人工智能友好"
    
    # 标点符号前的常用词
    ["点长度"]="点长度"
    ["点映射"]="点映射"
    ["点迭代"]="点迭代"
    ["点反转"]="点反转"
    ["点头部"]="点头部"
    ["点存在"]="点存在"
    ["点循环"]="点循环"
    ["点第"]="点第"
    ["点of"]="点转换为"
    ["点code"]="点编码"
    ["点concat"]="点连接"
    ["点gettimeofday"]="点获取时间"
    ["v2点0"]="版本二点零"
    ["3点14"]="三点一四"
    ["100点0"]="一百点零"
    ["4e00"]="四千八百"
    ["9fff"]="九千九百九十九"
    ["x4e00"]="编码四千八百"
    ["x9fff"]="编码九千九百九十九"
    
    # 常见英文单词和短语
    ["to "]="到 "
    [" to "]=" 到 "
    ["ERROR"]="错误"
    ["DEBUG"]="调试"
    ["INFO"]="信息"
    ["WARNING"]="警告"
    ["WARN"]="警告"
    ["FAIL"]="失败"
    ["PASS"]="通过"
    ["SUCCESS"]="成功"
    ["TRUE"]="真"
    ["FALSE"]="假"
    ["NULL"]="空"
    ["NONE"]="无"
    ["EMPTY"]="空"
    ["FULL"]="满"
    ["START"]="开始"
    ["END"]="结束"
    ["BEGIN"]="开始"
    ["FINISH"]="完成"
    ["INIT"]="初始化"
    ["CONFIG"]="配置"
    ["SETUP"]="设置"
    ["TEST"]="测试"
    ["DEMO"]="演示"
    ["EXAMPLE"]="示例"
    ["SAMPLE"]="样本"
    ["DEFAULT"]="默认"
    ["CUSTOM"]="自定义"
    ["STANDARD"]="标准"
    ["BASIC"]="基础"
    ["ADVANCED"]="高级"
    ["SIMPLE"]="简单"
    ["COMPLEX"]="复杂"
    ["MAIN"]="主要"
    ["HELPER"]="辅助"
    ["UTIL"]="工具"
    ["LIBRARY"]="库"
    ["MODULE"]="模块"
    ["PACKAGE"]="包"
    ["IMPORT"]="导入"
    ["EXPORT"]="导出"
    ["PUBLIC"]="公开"
    ["PRIVATE"]="私有"
    ["PROTECTED"]="保护"
    ["STATIC"]="静态"
    ["DYNAMIC"]="动态"
    ["GLOBAL"]="全局"
    ["LOCAL"]="本地"
    ["TEMP"]="临时"
    ["TMP"]="临时"
    ["CACHE"]="缓存"
    ["BUFFER"]="缓冲"
    ["QUEUE"]="队列"
    ["STACK"]="栈"
    ["HEAP"]="堆"
    ["TREE"]="树"
    ["GRAPH"]="图"
    ["LIST"]="列表"
    ["ARRAY"]="数组"
    ["VECTOR"]="向量"
    ["MATRIX"]="矩阵"
    ["TABLE"]="表"
    ["MAP"]="映射"
    ["SET"]="集合"
    ["PAIR"]="对"
    ["TUPLE"]="元组"
    ["STRUCT"]="结构"
    ["CLASS"]="类"
    ["OBJECT"]="对象"
    ["INSTANCE"]="实例"
    ["TYPE"]="类型"
    ["ENUM"]="枚举"
    ["UNION"]="联合"
    ["INTERFACE"]="接口"
    ["ABSTRACT"]="抽象"
    ["CONCRETE"]="具体"
    ["VIRTUAL"]="虚拟"
    ["OVERRIDE"]="覆盖"
    ["INHERIT"]="继承"
    ["EXTEND"]="扩展"
    ["IMPLEMENT"]="实现"
    ["CALL"]="调用"
    ["INVOKE"]="调用"
    ["EXECUTE"]="执行"
    ["RUN"]="运行"
    ["STOP"]="停止"
    ["PAUSE"]="暂停"
    ["RESUME"]="恢复"
    ["RESTART"]="重启"
    ["RESET"]="重置"
    ["CLEAR"]="清除"
    ["DELETE"]="删除"
    ["REMOVE"]="移除"
    ["ADD"]="添加"
    ["INSERT"]="插入"
    ["UPDATE"]="更新"
    ["MODIFY"]="修改"
    ["CHANGE"]="改变"
    ["REPLACE"]="替换"
    ["SWAP"]="交换"
    ["MOVE"]="移动"
    ["COPY"]="复制"
    ["CLONE"]="克隆"
    ["DUPLICATE"]="复制"
    ["MERGE"]="合并"
    ["SPLIT"]="分割"
    ["JOIN"]="连接"
    ["CONCAT"]="连接"
    ["APPEND"]="追加"
    ["PREPEND"]="前置"
    ["PUSH"]="推入"
    ["POP"]="弹出"
    ["PEEK"]="查看"
    ["SEARCH"]="搜索"
    ["FIND"]="查找"
    ["LOCATE"]="定位"
    ["GET"]="获取"
    ["SET"]="设置"
    ["PUT"]="放置"
    ["FETCH"]="获取"
    ["LOAD"]="加载"
    ["SAVE"]="保存"
    ["STORE"]="存储"
    ["READ"]="读取"
    ["WRITE"]="写入"
    ["OPEN"]="打开"
    ["CLOSE"]="关闭"
    ["LOCK"]="锁定"
    ["UNLOCK"]="解锁"
    ["ENABLE"]="启用"
    ["DISABLE"]="禁用"
    ["ACTIVATE"]="激活"
    ["DEACTIVATE"]="停用"
    ["VALID"]="有效"
    ["INVALID"]="无效"
    ["LEGAL"]="合法"
    ["ILLEGAL"]="非法"
    ["CORRECT"]="正确"
    ["INCORRECT"]="不正确"
    ["RIGHT"]="正确"
    ["WRONG"]="错误"
    ["GOOD"]="好"
    ["BAD"]="坏"
    ["OK"]="好"
    ["OKAY"]="好"
    ["YES"]="是"
    ["NO"]="否"
    ["ON"]="开"
    ["OFF"]="关"
    ["UP"]="上"
    ["DOWN"]="下"
    ["LEFT"]="左"
    ["RIGHT"]="右"
    ["FRONT"]="前"
    ["BACK"]="后"
    ["TOP"]="顶"
    ["BOTTOM"]="底"
    ["FIRST"]="第一"
    ["LAST"]="最后"
    ["NEXT"]="下一个"
    ["PREVIOUS"]="上一个"
    ["PREV"]="上一个"
    ["CURRENT"]="当前"
    ["NEW"]="新"
    ["OLD"]="旧"
    ["LATEST"]="最新"
    ["OLDEST"]="最旧"
    ["MIN"]="最小"
    ["MAX"]="最大"
    ["MINIMUM"]="最小"
    ["MAXIMUM"]="最大"
    ["AVERAGE"]="平均"
    ["TOTAL"]="总计"
    ["SUM"]="求和"
    ["COUNT"]="计数"
    ["SIZE"]="大小"
    ["LENGTH"]="长度"
    ["WIDTH"]="宽度"
    ["HEIGHT"]="高度"
    ["DEPTH"]="深度"
    ["WEIGHT"]="重量"
    ["VOLUME"]="体积"
    ["AREA"]="面积"
    ["RADIUS"]="半径"
    ["DIAMETER"]="直径"
    ["ANGLE"]="角度"
    ["SPEED"]="速度"
    ["TIME"]="时间"
    ["DATE"]="日期"
    ["YEAR"]="年"
    ["MONTH"]="月"
    ["DAY"]="日"
    ["HOUR"]="小时"
    ["MINUTE"]="分钟"
    ["SECOND"]="秒"
    ["MILLISECOND"]="毫秒"
    ["MICROSECOND"]="微秒"
    ["NANOSECOND"]="纳秒"
)

# 清理函数：只清理非注释行，排除C代码字符串
clean_file() {
    local file="$1"
    local temp_file=$(mktemp)
    local modified=false
    
    echo "🔧 处理文件: $file"
    
    # 逐行处理文件
    while IFS= read -r line || [[ -n "$line" ]]; do
        # 检查是否是注释行
        if [[ "$line" =~ ^[[:space:]]*# ]] || [[ "$line" =~ ^[[:space:]]*// ]] || [[ "$line" =~ ^\* ]]; then
            # 注释行保持原样
            echo "$line" >> "$temp_file"
        # 检查是否包含C代码片段（包含include、main、printf、return等关键字的字符串）
        elif [[ "$line" =~ (include|main|printf|return|stdio|void|int|char|float|double).*『.*』 ]] || [[ "$line" =~ 『.*(include|main|printf|return|stdio|void|int|char|float|double) ]]; then
            # 包含C代码的行保持原样
            echo "$line" >> "$temp_file"
        else
            # 非注释行且非C代码进行ASCII字符替换
            new_line="$line"
            
            # 首先替换常见的英文序列
            for old_seq in "${!sequence_map[@]}"; do
                new_seq="${sequence_map[$old_seq]}"
                if [[ "$new_line" == *"$old_seq"* ]]; then
                    new_line="${new_line//$old_seq/$new_seq}"
                    modified=true
                fi
            done
            
            # 然后替换单个字符
            for old_char in "${!char_map[@]}"; do
                new_char="${char_map[$old_char]}"
                if [[ "$new_line" == *"$old_char"* ]]; then
                    new_line="${new_line//$old_char/$new_char}"
                    modified=true
                fi
            done
            
            echo "$new_line" >> "$temp_file"
        fi
    done < "$file"
    
    # 如果文件被修改，则替换原文件
    if $modified; then
        mv "$temp_file" "$file"
        echo "  ✅ 已清理"
    else
        rm "$temp_file"
        echo "  ⏭️  无需清理"
    fi
}

# 查找并处理所有.ly文件
echo ""
echo "🔍 搜索.ly文件..."
LY_FILES=$(find . -name "*.ly" -type f)

if [ -z "$LY_FILES" ]; then
    echo "❌ 未找到任何.ly文件"
    exit 1
fi

file_count=$(echo "$LY_FILES" | wc -l)
echo "📊 找到 $file_count 个.ly文件"
echo ""

# 处理每个文件
processed=0
for file in $LY_FILES; do
    processed=$((processed + 1))
    echo "[$processed/$file_count]"
    clean_file "$file"
done

echo ""
echo "🎉 ASCII字符清理完成！"
echo "📊 处理统计:"
echo "  - 处理的文件: $file_count"
echo "  - 保留的内容: 注释中的ASCII字符"
echo ""
echo "💡 提示: 运行 './scripts/check_ascii_chars.sh' 验证清理结果"