(library
 (public_name yyocamlc.poetry.rhyme_data)
 (name poetry_rhyme_data)
 (libraries poetry_core)
 (modules
  ;; Core utilities
  rhyme_data_core
  ;; Individual rhyme group data modules
  an_rhyme_data
  si_rhyme_data
  tian_rhyme_data
  wang_rhyme_data
  qu_rhyme_data
  yu_rhyme_data
  hua_rhyme_data
  feng_rhyme_data
  yue_rhyme_data
  jiang_rhyme_data
  hui_rhyme_data
  ;; Unified registry
  rhyme_data_registry))
