(** 骆言词法分析器接口 - Chinese Programming Language Lexer Interface *)

(** 词元类型 *)
type token =
  (* 字面量 *)
  | IntToken of int
  | FloatToken of float
  | ChineseNumberToken of string (* 中文数字：一二三四五六七八九点 *)
  | StringToken of string
  | BoolToken of bool
  (* 标识符 *)
  | QuotedIdentifierToken of string (* 「标识符」 - 所有标识符必须引用 *)
  | IdentifierTokenSpecial of string (* 特殊保护的标识符，如"数值" *)
  (* 关键字 *)
  | LetKeyword (* 让 - let *)
  | RecKeyword (* 递归 - rec *)
  | InKeyword (* 在 - in *)
  | FunKeyword (* 函数 - fun *)
  | IfKeyword (* 如果 - if *)
  | ThenKeyword (* 那么 - then *)
  | ElseKeyword (* 否则 - else *)
  | MatchKeyword (* 匹配 - match *)
  | WithKeyword (* 与 - with *)
  | OtherKeyword (* 其他 - other/wildcard *)
  | TypeKeyword (* 类型 - type *)
  | PrivateKeyword (* 私有 - private *)
  | TrueKeyword (* 真 - true *)
  | FalseKeyword (* 假 - false *)
  | AndKeyword (* 并且 - and *)
  | OrKeyword (* 或者 - or *)
  | NotKeyword (* 非 - not *)
  (* 语义类型系统关键字 *)
  | AsKeyword (* 作为 - as *)
  | CombineKeyword (* 组合 - combine *)
  | WithOpKeyword (* 以及 - with_op *)
  | WhenKeyword (* 当 - when *)
  (* 错误恢复关键字 *)
  | OrElseKeyword (* 否则返回 - or_else *)
  | WithDefaultKeyword (* 默认为 - with_default *)
  (* 异常处理关键字 *)
  | ExceptionKeyword (* 异常 - exception *)
  | RaiseKeyword (* 抛出 - raise *)
  | TryKeyword (* 尝试 - try *)
  | CatchKeyword (* 捕获 - catch/with *)
  | FinallyKeyword (* 最终 - finally *)
  (* 类型关键字 *)
  | OfKeyword (* of - for type constructors *)
  (* 模块系统关键字 *)
  | ModuleKeyword (* 模块 - module *)
  | ModuleTypeKeyword (* 模块类型 - module type *)
  | SigKeyword (* 签名 - sig *)
  | EndKeyword (* 结束 - end *)
  | FunctorKeyword (* 函子 - functor *)
  (* 可变性关键字 *)
  | RefKeyword (* 引用 - ref *)
  (* 新增模块系统关键字 *)
  | IncludeKeyword (* 包含 - include *)
  (* 宏系统关键字 *)
  | MacroKeyword (* 宏 - macro *)
  | ExpandKeyword (* 展开 - expand *)
  (* wenyan风格关键字 *)
  | HaveKeyword (* 吾有 - I have *)
  | OneKeyword (* 一 - one *)
  | NameKeyword (* 名曰 - name it *)
  | SetKeyword (* 设 - set *)
  | AlsoKeyword (* 也 - also/end particle *)
  | ThenGetKeyword (* 乃 - then/thus *)
  | CallKeyword (* 曰 - called/said *)
  | ValueKeyword (* 其值 - its value *)
  | AsForKeyword (* 为 - as for/regarding *)
  | NumberKeyword (* 数 - number *)
  (* wenyan扩展关键字 *)
  | WantExecuteKeyword (* 欲行 - want to execute *)
  | MustFirstGetKeyword (* 必先得 - must first get *)
  | ForThisKeyword (* 為是 - for this *)
  | TimesKeyword (* 遍 - times/iterations *)
  | EndCloudKeyword (* 云云 - end marker *)
  | IfWenyanKeyword (* 若 - if (wenyan style) *)
  | ThenWenyanKeyword (* 者 - then particle *)
  | GreaterThanWenyan (* 大于 - greater than *)
  | LessThanWenyan (* 小于 - less than *)
  (* 古雅体关键字 - Ancient Chinese Literary Style *)
  | AncientDefineKeyword (* 夫...者 - ancient function definition *)
  | AncientEndKeyword (* 是谓 - ancient end marker *)
  | AncientAlgorithmKeyword (* 算法 - algorithm *)
  | AncientCompleteKeyword (* 竟 - complete/finish *)
  | AncientObserveKeyword (* 观 - observe/examine *)
  | AncientNatureKeyword (* 性 - nature/essence *)
  | AncientIfKeyword (* 若 - if (ancient style) *)
  | AncientThenKeyword (* 则 - then (ancient) *)
  | AncientOtherwiseKeyword (* 余者 - otherwise/others *)
  | AncientAnswerKeyword (* 答 - answer/return *)
  | AncientRecursiveKeyword (* 递归 - recursive (ancient) *)
  | AncientCombineKeyword (* 合 - combine *)
  | AncientAsOneKeyword (* 为一 - as one *)
  | AncientTakeKeyword (* 取 - take/get *)
  | AncientReceiveKeyword (* 受 - receive *)
  | AncientParticleOf (* 之 - possessive particle *)
  | AncientParticleFun (* 焉 - function parameter particle *)
  | AncientParticleThe (* 其 - its/the *)
  | AncientCallItKeyword (* 名曰 - call it *)
  | AncientListStartKeyword (* 列开始 - list start *)
  | AncientListEndKeyword (* 列结束 - list end *)
  | AncientItsFirstKeyword (* 其一 - its first *)
  | AncientItsSecondKeyword (* 其二 - its second *)
  | AncientItsThirdKeyword (* 其三 - its third *)
  | AncientEmptyKeyword (* 空空如也 - empty as void *)
  | AncientHasHeadTailKeyword (* 有首有尾 - has head and tail *)
  | AncientHeadNameKeyword (* 首名为 - head named as *)
  | AncientTailNameKeyword (* 尾名为 - tail named as *)
  | AncientThusAnswerKeyword (* 则答 - thus answer *)
  | AncientAddToKeyword (* 并加 - and add *)
  | AncientObserveEndKeyword (* 观察毕 - observation complete *)
  | AncientBeginKeyword (* 始 - begin *)
  | AncientEndCompleteKeyword (* 毕 - complete *)
  | AncientIsKeyword (* 乃 - is/thus *)
  | AncientArrowKeyword (* 故 - therefore/thus *)
  | AncientWhenKeyword (* 当 - when *)
  | AncientCommaKeyword (* 且 - and/also *)
  | AncientPeriodKeyword (* 也 - particle for end of statement *)
  | AfterThatKeyword (* 而后 - after that/then *)
  (* 自然语言函数定义关键字 *)
  | DefineKeyword (* 定义 - define *)
  | AcceptKeyword (* 接受 - accept *)
  | ReturnWhenKeyword (* 时返回 - return when *)
  | ElseReturnKeyword (* 否则返回 - else return *)
  | MultiplyKeyword (* 乘以 - multiply *)
  | DivideKeyword (* 除以 - divide *)
  | AddToKeyword (* 加上 - add to *)
  | SubtractKeyword (* 减去 - subtract *)
  | IsKeyword (* 为 - is *)
  | EqualToKeyword (* 等于 - equal to *)
  | LessThanEqualToKeyword (* 小于等于 - less than or equal to *)
  | FirstElementKeyword (* 首元素 - first element *)
  | RemainingKeyword (* 剩余 - remaining *)
  | EmptyKeyword (* 空 - empty *)
  | CharacterCountKeyword (* 字符数量 - character count *)
  | OfParticle (* 之 - possessive particle *)
  | TopicMarker (* 者 - topic marker *)
  (* 新增自然语言函数定义关键字 *)
  | InputKeyword (* 输入 - input *)
  | OutputKeyword (* 输出 - output *)
  | MinusOneKeyword (* 减一 - minus one *)
  | PlusKeyword (* 加 - plus *)
  | WhereKeyword (* 其中 - where *)
  | SmallKeyword (* 小 - small *)
  | ShouldGetKeyword (* 应得 - should get *)
  | IntTypeKeyword (* 整数 - int *)
  | FloatTypeKeyword (* 浮点数 - float *)
  | StringTypeKeyword (* 字符串 - string *)
  | BoolTypeKeyword (* 布尔 - bool *)
  | UnitTypeKeyword (* 单元 - unit *)
  | ListTypeKeyword (* 列表 - list *)
  | ArrayTypeKeyword (* 数组 - array *)
  
  (* 多态变体关键字 *)
  | VariantKeyword (* 变体 - variant *)
  | TagKeyword (* 标签 - tag (for polymorphic variants) *)
  
  
  (* 运算符 *)
  | Plus (* + *)
  | Minus (* - *)
  | Multiply (* * *)
  | Star (* * - alias for Multiply *)
  | Divide (* / *)
  | Slash (* / - alias for Divide *)
  | Modulo (* % *)
  | Concat (* ^ - 字符串连接 *)
  | Assign (* = *)
  | Equal (* == *)
  | NotEqual (* <> *)
  | Less (* < *)
  | LessEqual (* <= *)
  | Greater (* > *)
  | GreaterEqual (* >= *)
  | Arrow (* -> *)
  | DoubleArrow (* => *)
  | Dot (* . *)
  | DoubleDot (* .. *)
  | TripleDot (* ... *)
  | Bang (* ! - for dereferencing *)
  | RefAssign (* := - for reference assignment *)
  (* 分隔符 *)
  | LeftParen (* ( *)
  | RightParen (* ) *)
  | LeftBracket (* [ *)
  | RightBracket (* ] *)
  | LeftBrace (* { *)
  | RightBrace (* } *)
  | Comma (* , *)
  | Semicolon (* ; *)
  | Colon (* : *)
  | QuestionMark (* ? *)
  | Tilde (* ~ *)
  | Pipe (* | *)
  | Underscore (* _ *)
  | LeftArray (* [| *)
  | RightArray (* |] *)
  | AssignArrow (* <- *)
  | LeftQuote (* 「 *)
  | RightQuote (* 」 *)
  
  (* 中文标点符号 *)
  | ChineseLeftParen (* （ *)
  | ChineseRightParen (* ） *)
  | ChineseLeftBracket (* 「 - 用于列表 *)
  | ChineseRightBracket (* 」 - 用于列表 *)
  | ChineseComma (* ， *)
  | ChineseSemicolon (* ； *)
  | ChineseColon (* ： *)
  | ChineseDoubleColon (* ：： - 类型注解 *)
  | ChinesePipe (* ｜ *)
  | ChineseLeftArray (* 「| *)
  | ChineseRightArray (* |」 *)
  | ChineseArrow (* → *)
  | ChineseDoubleArrow (* ⇒ *)
  | ChineseAssignArrow (* ← *)
  
  (* 特殊 *)
  | Newline
  | EOF
[@@deriving show, eq]

(** 位置信息 *)
type position = { 
  line : int; 
  column : int; 
  filename : string 
} [@@deriving show, eq]

(** 带位置的词元 *)
type positioned_token = token * position [@@deriving show, eq]

(** 词法错误 *)
exception LexError of string * position

(** 查找关键字
    @param keyword 关键字字符串
    @return 对应的词元，如果不是关键字则返回None *)
val find_keyword : string -> token option

(** 词法分析主函数 
    @param input 输入源代码字符串
    @param filename 文件名（用于错误报告）
    @return 带位置信息的词元列表 *)
val tokenize : string -> string -> positioned_token list